// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: ephemerd.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_ephemerd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveJobs    int32                  `protobuf:"varint,2,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Draining      bool                   `protobuf:"varint,4,opt,name=draining,proto3" json:"draining,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_ephemerd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *StatusResponse) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *StatusResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

func (x *StatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_ephemerd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{2}
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_ephemerd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{3}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_ephemerd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	RunnerId      int64                  `protobuf:"varint,5,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Pid           uint32                 `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // RFC3339
	Uptime        string                 `protobuf:"bytes,9,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_ephemerd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{5}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Job) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Job) GetRunnerId() int64 {
	if x != nil {
		return x.RunnerId
	}
	return 0
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Job) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Job) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type KillJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillJobRequest) Reset() {
	*x = KillJobRequest{}
	mi := &file_ephemerd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillJobRequest) ProtoMessage() {}

func (x *KillJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillJobRequest.ProtoReflect.Descriptor instead.
func (*KillJobRequest) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{6}
}

func (x *KillJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type KillJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillJobResponse) Reset() {
	*x = KillJobResponse{}
	mi := &file_ephemerd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillJobResponse) ProtoMessage() {}

func (x *KillJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillJobResponse.ProtoReflect.Descriptor instead.
func (*KillJobResponse) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{7}
}

type GetJobLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobLogsRequest) Reset() {
	*x = GetJobLogsRequest{}
	mi := &file_ephemerd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsRequest) ProtoMessage() {}

func (x *GetJobLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsRequest.ProtoReflect.Descriptor instead.
func (*GetJobLogsRequest) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobLogsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetJobLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_ephemerd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ephemerd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_ephemerd_proto_rawDescGZIP(), []int{9}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ephemerd_proto protoreflect.FileDescriptor

const file_ephemerd_proto_rawDesc = "" +
	"\n" +
	"\x0eephemerd.proto\x12\vephemerd.v1\"\x0f\n" +
	"\rStatusRequest\"\xa4\x01\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vactive_jobs\x18\x02 \x01(\x05R\n" +
	"activeJobs\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\x12\x1a\n" +
	"\bdraining\x18\x04 \x01(\bR\bdraining\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\"\x11\n" +
	"\x0fListJobsRequest\"8\n" +
	"\x10ListJobsResponse\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.ephemerd.v1.JobR\x04jobs\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd1\x01\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1b\n" +
	"\trunner_id\x18\x05 \x01(\x03R\brunnerId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\a \x01(\rR\x03pid\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x16\n" +
	"\x06uptime\x18\t \x01(\tR\x06uptime\" \n" +
	"\x0eKillJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fKillJobResponse\";\n" +
	"\x11GetJobLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"\x1e\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xda\x02\n" +
	"\aControl\x12A\n" +
	"\x06Status\x12\x1a.ephemerd.v1.StatusRequest\x1a\x1b.ephemerd.v1.StatusResponse\x12G\n" +
	"\bListJobs\x12\x1c.ephemerd.v1.ListJobsRequest\x1a\x1d.ephemerd.v1.ListJobsResponse\x126\n" +
	"\x06GetJob\x12\x1a.ephemerd.v1.GetJobRequest\x1a\x10.ephemerd.v1.Job\x12D\n" +
	"\aKillJob\x12\x1b.ephemerd.v1.KillJobRequest\x1a\x1c.ephemerd.v1.KillJobResponse\x12E\n" +
	"\n" +
	"GetJobLogs\x12\x1e.ephemerd.v1.GetJobLogsRequest\x1a\x15.ephemerd.v1.LogChunk0\x01B(Z&github.com/ephpm/ephemerd/api/v1;apiv1b\x06proto3"

var (
	file_ephemerd_proto_rawDescOnce sync.Once
	file_ephemerd_proto_rawDescData []byte
)

func file_ephemerd_proto_rawDescGZIP() []byte {
	file_ephemerd_proto_rawDescOnce.Do(func() {
		file_ephemerd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ephemerd_proto_rawDesc), len(file_ephemerd_proto_rawDesc)))
	})
	return file_ephemerd_proto_rawDescData
}

var file_ephemerd_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ephemerd_proto_goTypes = []any{
	(*StatusRequest)(nil),     // 0: ephemerd.v1.StatusRequest
	(*StatusResponse)(nil),    // 1: ephemerd.v1.StatusResponse
	(*ListJobsRequest)(nil),   // 2: ephemerd.v1.ListJobsRequest
	(*ListJobsResponse)(nil),  // 3: ephemerd.v1.ListJobsResponse
	(*GetJobRequest)(nil),     // 4: ephemerd.v1.GetJobRequest
	(*Job)(nil),               // 5: ephemerd.v1.Job
	(*KillJobRequest)(nil),    // 6: ephemerd.v1.KillJobRequest
	(*KillJobResponse)(nil),   // 7: ephemerd.v1.KillJobResponse
	(*GetJobLogsRequest)(nil), // 8: ephemerd.v1.GetJobLogsRequest
	(*LogChunk)(nil),          // 9: ephemerd.v1.LogChunk
}
var file_ephemerd_proto_depIdxs = []int32{
	5, // 0: ephemerd.v1.ListJobsResponse.jobs:type_name -> ephemerd.v1.Job
	0, // 1: ephemerd.v1.Control.Status:input_type -> ephemerd.v1.StatusRequest
	2, // 2: ephemerd.v1.Control.ListJobs:input_type -> ephemerd.v1.ListJobsRequest
	4, // 3: ephemerd.v1.Control.GetJob:input_type -> ephemerd.v1.GetJobRequest
	6, // 4: ephemerd.v1.Control.KillJob:input_type -> ephemerd.v1.KillJobRequest
	8, // 5: ephemerd.v1.Control.GetJobLogs:input_type -> ephemerd.v1.GetJobLogsRequest
	1, // 6: ephemerd.v1.Control.Status:output_type -> ephemerd.v1.StatusResponse
	3, // 7: ephemerd.v1.Control.ListJobs:output_type -> ephemerd.v1.ListJobsResponse
	5, // 8: ephemerd.v1.Control.GetJob:output_type -> ephemerd.v1.Job
	7, // 9: ephemerd.v1.Control.KillJob:output_type -> ephemerd.v1.KillJobResponse
	9, // 10: ephemerd.v1.Control.GetJobLogs:output_type -> ephemerd.v1.LogChunk
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ephemerd_proto_init() }
func file_ephemerd_proto_init() {
	if File_ephemerd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ephemerd_proto_rawDesc), len(file_ephemerd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ephemerd_proto_goTypes,
		DependencyIndexes: file_ephemerd_proto_depIdxs,
		MessageInfos:      file_ephemerd_proto_msgTypes,
	}.Build()
	File_ephemerd_proto = out.File
	file_ephemerd_proto_goTypes = nil
	file_ephemerd_proto_depIdxs = nil
}
